In [1]:
import pandas as pd
import numpy as np

In [2]:
data_path = '..\\data\\'

In [3]:
X_train_val = np.load(data_path + 'X_train.npy')
y_train_val = np.load(data_path + 'y_train.npy')
X_test = np.load(data_path + 'X_test.npy')
y_test = np.load(data_path + 'y_test.npy')

Возьмём одну серию наблюдений для описания генерируемых предикторов

In [4]:
sample = pd.DataFrame(X_train_val[12])

In [5]:
sample

,0,1,2,3,4,5,6,7,8
0,1.019400,-0.128588,0.078723,-0.001608,0.002257,0.002424,0.003297,0.002884,0.003029
1,1.019465,-0.129745,0.077025,-0.001525,0.001117,0.000687,-0.001468,0.002167,0.000735
2,1.020643,-0.128953,0.075283,-0.000329,0.001926,-0.001095,-0.006687,0.000814,-0.000047
3,1.022011,-0.128970,0.079297,0.001057,0.001927,0.002880,-0.006653,0.003478,0.001206
4,1.022496,-0.130122,0.080057,0.001560,0.000793,0.003601,-0.009488,0.002297,0.002822
...,...,...,...,...,...,...,...,...,...
123,1.022605,-0.134355,0.071776,0.001657,0.002845,-0.002536,0.005342,-0.001952,0.001321
124,1.022188,-0.132734,0.073651,0.001243,0.004447,-0.000634,0.003543,-0.000729,-0.002660
125,1.022221,-0.131704,0.073340,0.001279,0.005457,-0.000918,0.001422,0.002820,-0.003250
126,1.022120,-0.131100,0.075476,0.001181,0.006038,0.001245,-0.002472,0.003765,0.002388
127,1.022180,-0.130712,0.076335,0.001243,0.006402,0.002130,-0.004282,0.003829,0.006102

Посчитаем базовые статистики, которые станут первыми признаками

In [6]:
sample.describe()

,0,1,2,3,4,5,6,7,8
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,1.021178,-0.135833,0.074728,0.000182,-0.001719,-0.001461,-0.001541,-0.000724,-0.000066
std,0.001630,0.003405,0.003691,0.001700,0.004351,0.003696,0.005665,0.004224,0.004194
min,1.016271,-0.143184,0.065428,-0.004877,-0.012071,-0.009701,-0.013384,-0.011601,-0.010315
25%,1.019884,-0.138211,0.072088,-0.001002,-0.005231,-0.003746,-0.006602,-0.003610,-0.002808
50%,1.021555,-0.136143,0.074840,0.000594,-0.001805,-0.001434,-0.001715,-0.000902,-0.000006
75%,1.022232,-0.134338,0.077136,0.001366,0.002184,0.001035,0.003306,0.002318,0.002884
max,1.025468,-0.127627,0.084949,0.004692,0.009334,0.008819,0.008517,0.009499,0.009939

Сделаем разностное преобразование первого порядка

In [7]:
sample_diff = sample.diff().dropna()

In [8]:
sample_diff

,0,1,2,3,4,5,6,7,8
1,0.000065,-0.001157,-0.001698,0.000082,-0.001140,-0.001737,-0.004765,-0.000717,-0.002294
2,0.001178,0.000792,-0.001742,0.001196,0.000809,-0.001782,-0.005219,-0.001353,-0.000782
3,0.001368,-0.000017,0.004014,0.001386,0.000001,0.003975,0.000035,0.002664,0.001253
4,0.000485,-0.001152,0.000760,0.000503,-0.001134,0.000721,-0.002835,-0.001181,0.001616
5,-0.000269,-0.001330,0.001866,-0.000250,-0.001312,0.001828,0.001748,-0.003537,0.000099
...,...,...,...,...,...,...,...,...,...
123,0.000830,0.000612,0.000850,0.000833,0.000595,0.000878,0.000907,-0.005993,0.001874
124,-0.000417,0.001621,0.001875,-0.000413,0.001602,0.001902,-0.001799,0.001223,-0.003981
125,0.000033,0.001030,-0.000311,0.000035,0.001009,-0.000284,-0.002121,0.003549,-0.000590
126,-0.000101,0.000604,0.002136,-0.000098,0.000582,0.002163,-0.003894,0.000945,0.005638
127,0.000060,0.000388,0.000859,0.000063,0.000364,0.000885,-0.001810,0.000064,0.003713

Базовые статистики над разностным преобразованием сигналов также включим в список предикторов

Добавим вил тренда для сигнала с каждого датчика как ещё один признак

Для этого сначала посчитаем скользящее среднее для окна в 20 наблюдений

In [9]:
rolling_mean = sample.rolling(window=20).mean().dropna()

In [10]:
rolling_mean

,0,1,2,3,4,5,6,7,8
19,1.022274,-0.132908,0.077081,0.001423,-0.001900,0.000414,-0.006154,-0.003201,0.004322
20,1.022372,-0.133489,0.076946,0.001535,-0.002464,0.000241,-0.006398,-0.003925,0.004510
21,1.022437,-0.133933,0.076664,0.001614,-0.002892,-0.000077,-0.006642,-0.004376,0.004633
22,1.022537,-0.134412,0.076315,0.001727,-0.003353,-0.000463,-0.006977,-0.004645,0.004634
23,1.022654,-0.134873,0.075839,0.001855,-0.003796,-0.000975,-0.007146,-0.004994,0.004638
...,...,...,...,...,...,...,...,...,...
123,1.020514,-0.135669,0.073615,-0.000463,0.001574,-0.001001,-0.000752,0.004861,-0.005472
124,1.020491,-0.135608,0.073748,-0.000482,0.001636,-0.000835,-0.000347,0.004538,-0.005280
125,1.020590,-0.135409,0.073662,-0.000380,0.001835,-0.000888,-0.000135,0.004204,-0.005184
126,1.020757,-0.135193,0.073522,-0.000211,0.002048,-0.000995,-0.000163,0.003958,-0.004807
127,1.020836,-0.134898,0.073735,-0.000129,0.002337,-0.000751,-0.000215,0.003934,-0.004204

Определим восходящий тренд: последнее наблюдение больше первого, и они отличаются более чем на 2 стандартных отклонения скользящей средней <br>
Определим нисходящий тренд: последнее наблюдение меньше первого, и они отличаются более чем на 2 стандартных отклонения скользящей средней <br>
Иначе фиксируем отсутствие тренда

In [11]:
trend_series = rolling_mean.apply(lambda column: 'upward' if column.iloc[-1] - column.iloc[0] > 0 else 'downward' if np.abs(column.iloc[-1] - column.iloc[0]) > 2*column.std() else 'flat', axis=0)

In [12]:
trend_series

0        flat
1        flat
2    downward
3        flat
4      upward
5        flat
6      upward
7      upward
8    downward
dtype: object

Обучим One-hot encoder кодировать эти значения

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
oh_encoder = OneHotEncoder()

In [15]:
encoder_fit_array = trend_series.values[:, np.newaxis]

In [16]:
encoder_fit_array

array([['flat'],
       ['flat'],
       ['downward'],
       ['flat'],
       ['upward'],
       ['flat'],
       ['upward'],
       ['upward'],
       ['downward']], dtype=object)

На выходе кодировщика получим матрицу

In [17]:
print(oh_encoder.fit_transform(encoder_fit_array).toarray())

[[0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]

Рассчитаем признаки для каждой серии наблюдений

In [18]:
features_train_val = []
for i in range(X_train_val.shape[0]):
    sample = pd.DataFrame(X_train_val[i])
    mean_values = np.mean(sample, axis=0)
    std_values = np.std(sample, axis=0)
    min_values = np.min(sample, axis=0)
    max_values = np.max(sample, axis=0)
    min_max_diff = max_values - min_values
    
    sample_diff = pd.DataFrame(sample).diff().dropna()
    sample_diff_mean = sample_diff.mean(axis=0).values
    sample_diff_std = sample_diff.std(axis=0).values
    sample_diff_max = sample_diff.max(axis=0).values
    sample_diff_min = sample_diff.min(axis=0).values
    sample_diff_max_min_range = sample_diff_max - sample_diff_min
    
    rolling_mean = sample.rolling(window=20).mean().dropna()
    trend_series = rolling_mean.apply(lambda column: 'upward' if column.iloc[-1] - column.iloc[0] > 0 else 'downward' if np.abs(column.iloc[-1] - column.iloc[0]) > 2*column.std() else 'flat', axis=0)
    trend_series_values = trend_series.values[:, np.newaxis]
    
    trend_features = oh_encoder.transform(trend_series_values).toarray()
    trend_features = trend_features.reshape(-1)
    
    sample_features = np.hstack((mean_values, std_values, min_values, max_values, min_max_diff, 
                                 sample_diff_mean, sample_diff_std, sample_diff_min, sample_diff_max,
                                sample_diff_max_min_range, trend_features))
    
    features_train_val.append(sample_features)
features_train_val = np.stack(features_train_val)

Проверим, что размерность совпадает

In [19]:
assert features_train_val.shape[0] == X_train_val.shape[0]

Сохраним получившийся набор данных в файл

In [20]:
np.save(data_path + 'features_train_val.npy', features_train_val)

Повторим эти же действия для тестовой выборки

In [22]:
features_test = []
for i in range(X_test.shape[0]):
    sample = pd.DataFrame(X_test[i])
    mean_values = np.mean(sample, axis=0)
    std_values = np.std(sample, axis=0)
    min_values = np.min(sample, axis=0)
    max_values = np.max(sample, axis=0)
    min_max_diff = max_values - min_values
    
    sample_diff = pd.DataFrame(sample).diff().dropna()
    sample_diff_mean = sample_diff.mean(axis=0).values
    sample_diff_std = sample_diff.std(axis=0).values
    sample_diff_max = sample_diff.max(axis=0).values
    sample_diff_min = sample_diff.min(axis=0).values
    sample_diff_max_min_range = sample_diff_max - sample_diff_min
    
    rolling_mean = sample.rolling(window=20).mean().dropna()
    trend_series = rolling_mean.apply(lambda column: 'upward' if column.iloc[-1] - column.iloc[0] > 0 else 'downward' if np.abs(column.iloc[-1] - column.iloc[0]) > 2*column.std() else 'flat', axis=0)
    trend_series_values = trend_series.values[:, np.newaxis]
    
    trend_features = oh_encoder.transform(trend_series_values).toarray()
    trend_features = trend_features.reshape(-1)
    sample_features = np.hstack((mean_values, std_values, min_values, max_values, min_max_diff, 
                                 sample_diff_mean, sample_diff_std, sample_diff_min, sample_diff_max,
                                sample_diff_max_min_range, trend_features))
    
    features_test.append(sample_features)
features_test = np.stack(features_test)

In [23]:
assert features_test.shape[0] == X_test.shape[0]

In [24]:
np.save(data_path + 'features_test.npy', features_test)